//! Storage back-compat golden fixtures.
//!
//! Each `tests/fixtures/datadir-<tag>.tar.gz` is a data dir written by a released
//! broker version (generated by scripts/gen-compat-fixture.sh). This test opens
//! every one with the CURRENT broker and asserts it still recovers: no partition
//! is quarantined, the declared queue and durable stream are present, and the
//! messages that must survive a cold reopen come back intact. A failure means a
//! change broke the on-disk format for an older data dir - the guarantee the
//! fixtures exist to hold.
//!
//! Regenerate the current release's fixture with:
//!   scripts/gen-compat-fixture.sh <tag>

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;
use std::time::Duration;

use fibril_broker::broker::{Broker, BrokerConfig, ConsumerConfig};
use fibril_broker::queue_engine::{QueueEngine, StreamStore, StromaEngine};
use fibril_broker::storage::Partition;
use stroma_core::{KeratinConfig, SnapshotConfig, StromaKeratinConfig, TempDir, test_dir};
use uuid::Uuid;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

async fn open_broker_at(dir: &Path) -> Arc<Broker<StromaEngine>> {
    let engine = StromaEngine::open(
        dir,
        StromaKeratinConfig::from_message_log(KeratinConfig::test_default()),
        SnapshotConfig::default(),
    )
    .await
    .expect("engine opens and recovers the fixture");
    Broker::new(engine, BrokerConfig::default(), None)
}

/// Every committed golden data dir opens on the current broker and recovers the
/// state its manifest describes.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn golden_data_dirs_open_on_the_current_broker() {
    let fixtures = fixtures_dir();
    let mut archives: Vec<PathBuf> = std::fs::read_dir(&fixtures)
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "gz"))
        .collect();
    archives.sort();
    assert!(
        !archives.is_empty(),
        "no golden fixtures in {} - generate one with scripts/gen-compat-fixture.sh",
        fixtures.display()
    );

    for archive in archives {
        let name = archive.file_name().unwrap().to_string_lossy();
        // datadir-<tag>.tar.gz -> datadir-<tag>
        let stem = name
            .strip_suffix(".tar.gz")
            .unwrap_or_else(|| panic!("unexpected fixture name {name}"));
        let manifest_path = fixtures.join(format!("{stem}.manifest.json"));
        let manifest: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&manifest_path)
                .unwrap_or_else(|e| panic!("read manifest {}: {e}", manifest_path.display())),
        )
        .expect("manifest is valid json");

        let dir: TempDir = test_dir!("compat-fixture");
        let status = Command::new("tar")
            .arg("-xzf")
            .arg(&archive)
            .arg("-C")
            .arg(&dir.root)
            .status()
            .expect("system tar is available to unpack the fixture");
        assert!(status.success(), "unpacking {name} failed");
        let data_dir = dir.root.join("data");

        let broker = open_broker_at(&data_dir).await;

        // The core guarantee: recovery quarantines nothing. A quarantine is how a
        // decode or integrity failure surfaces, so an empty set means every log,
        // snapshot, and kind marker the old broker wrote still parses.
        let quarantined = broker.engine().quarantined_partitions();
        assert!(
            quarantined.is_empty(),
            "{name}: recovery quarantined partitions {quarantined:?}"
        );

        // The durable stream recovered as a stream on every partition.
        let stream = &manifest["stream"];
        let stream_topic = stream["topic"].as_str().unwrap();
        let stream_partitions = stream["partitions"].as_u64().unwrap() as u32;
        for partition in 0..stream_partitions {
            assert!(
                broker.engine().durable_is_stream(stream_topic, partition),
                "{name}: stream {stream_topic} partition {partition} did not recover as a stream"
            );
        }

        // The queue's recoverable messages come back, intact and identifiable.
        // recoverable_floor is the count that MUST redeliver on a cold open (the
        // ready messages the generator never received); inflight and delayed
        // timing is wall-clock dependent, so the assertion is a lower bound.
        let queue = &manifest["queue"];
        let queue_topic = queue["topic"].as_str().unwrap();
        let queue_group = queue["group"].as_str().unwrap();
        let queue_partitions = queue["partitions"].as_u64().unwrap() as u32;
        let payload_prefix = manifest["payload_prefix"].as_str().unwrap();
        let floor = manifest["recoverable_floor"].as_u64().unwrap() as usize;

        let mut drained = 0usize;
        for partition in 0..queue_partitions {
            let mut sub = broker
                .subscribe(
                    queue_topic,
                    Partition::new(partition),
                    Some(queue_group),
                    Uuid::now_v7(),
                    ConsumerConfig { prefetch: 64 },
                )
                .await
                .expect("subscribe to a recovered partition");
            while let Ok(Some(msg)) =
                tokio::time::timeout(Duration::from_millis(500), sub.recv()).await
            {
                let text = std::str::from_utf8(&msg.message.payload)
                    .expect("recovered payload is intact utf8");
                assert!(
                    text.starts_with(payload_prefix),
                    "{name}: recovered payload {text:?} is not a fixture payload"
                );
                drained += 1;
            }
            drop(sub);
        }
        assert!(
            drained >= floor,
            "{name}: recovered {drained} queue messages, expected at least {floor}"
        );

        broker.shutdown().await;
    }
}
